/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 09/09/2012 4:55:42 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;

using DocketPlace.Business.Framework;


namespace DocketPlace.Business
{
	/// <summary>
	/// This object represents the properties and methods of a Role.
	/// </summary>
	[Serializable()]
	[DebuggerDisplay("role_name: {role_name}")]
	public partial class Role
	{
		#region Public Properties
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _role_name = String.Empty;
		/// <summary>
		/// role_name
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(true, false, false)]
		public string role_name
		{
			[DebuggerStepThrough()]
			get { return this._role_name; }
			set 
			{
				if (this._role_name != value) 
				{
					this._role_name = value;
					this.IsDirty = true;	
					OnPropertyChanged("role_name");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _notes = String.Empty;
		/// <summary>
		/// notes
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public string notes
		{
			[DebuggerStepThrough()]
			get { return this._notes; }
			set 
			{
				if (this._notes != value) 
				{
					this._notes = value;
					this.IsDirty = true;	
					OnPropertyChanged("notes");
				}
			}
		}
		
		
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private EntityList<Permission> _permissionsByrole_name = null;
		/// <summary>
		/// A collection of Permission children objects
		/// </summary>
		public EntityList<Permission> PermissionsByrole_name
		{
			get 
			{
				if (_permissionsByrole_name == null) {
					_permissionsByrole_name = DocketPlace.Business.Permission.GetPermissionsByrole_name(this);
				}
				return _permissionsByrole_name;
			}
		}	
		#endregion
		
		#region Non-Public Properties
		/// <summary>
		/// Gets the SQL statement for an insert
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string InsertSPName
		{
			get 
			{
				return typeof(Role).Name + "Insert";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for an update by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string UpdateSPName
		{
			get
			{
				return typeof(Role).Name + "Update";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for a delete by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string DeleteSPName
		{
			get
			{
				return typeof(Role).Name + "Delete";
			}
		}
		#endregion
		
		#region Constructors
		/// <summary>
		/// The default protected constructor
		/// </summary>
		protected Role() { }
		#endregion
		
		#region Public Methods
		/// <summary>
		/// Creates a Permission for this Role object
		/// </summary>
		public Permission CreatePermission()
		{
			return DocketPlace.Business.Permission.CreatePermissionByrole_name(this);
		}
		

        /// <summary>
        /// Refreshes the entity with data from the data source. Child entity objects and entity list objects will be preserved (ie. they will not be replaced with new objects so that references to them are retained, such as bound data controls).
        /// </summary>
        public override void Refresh()
		{
			this.Replace(GetRole(this.role_name));
		}

		#endregion
		
		#region Non-Public Methods
		/// <summary>
		/// This is called before an entity is saved to ensure that any parent entities keys are set properly
		/// </summary>
		protected override void EnsureParentProperties()
		{
		}
		#endregion
		
		#region Static Properties
		/// <summary>
		/// A list of all fields for this entity in the database. It does not include the 
		/// select keyword, or the table information - just the fields. This can be used
		/// for new dynamic methods.
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		public static string SelectFieldList 
		{
			get 
			{
				return @"
	[Roles].[role_name],
	[Roles].[notes]
";
			}
		}
		
		
		/// <summary>
        /// Table Name
        /// </summary>
        public new static string TableName
        {
            get
            {
                return "Roles";
            }
        }

		#endregion
		
		#region Static Methods
		/// <summary>
		/// Insert a Role into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="role_name">role_name</param>
		/// <param name="notes">notes</param>
		public static void InsertRole(string @role_name, string @notes)
		{
            using (SqlHelper helper = new SqlHelper())
            {
                try
                {
                    helper.BeginTransaction();
            		InsertRole(@role_name, @notes, helper);
                    helper.Commit();
                }
                catch
                {
                    helper.Rollback();
                    throw;
                }
            }
		}

		/// <summary>
		/// Insert a Role into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="role_name">role_name</param>
		/// <param name="notes">notes</param>
		/// <param name="helper">helper</param>
		internal static void InsertRole(string @role_name, string @notes, SqlHelper @helper)
		{
			string commandText = "RoleInsert";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@role_name", EntityBase.GetDatabaseValue(@role_name)));
			parameters.Add(new SqlParameter("@notes", EntityBase.GetDatabaseValue(@notes)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Updates a Role into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="role_name">role_name</param>
		/// <param name="notes">notes</param>
		public static void UpdateRole(string @role_name, string @notes)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try
				{
					helper.BeginTransaction();
					UpdateRole(@role_name, @notes, helper);
					helper.Commit();
				}
				catch 
				{
					helper.Rollback();	
					throw;
				}
			}
		}
		
		/// <summary>
		/// Updates a Role into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="role_name">role_name</param>
		/// <param name="notes">notes</param>
		/// <param name="helper">helper</param>
		internal static void UpdateRole(string @role_name, string @notes, SqlHelper @helper)
		{
			string commandText = "RoleUpdate";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@role_name", EntityBase.GetDatabaseValue(@role_name)));
			parameters.Add(new SqlParameter("@notes", EntityBase.GetDatabaseValue(@notes)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Deletes a Role from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="role_name">role_name</param>
		public static void DeleteRole(string @role_name)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try 
				{
					helper.BeginTransaction();
					DeleteRole(@role_name, helper);
					helper.Commit();
				} 
				catch 
				{
					helper.Rollback();
					throw;
				}
			}
		}
		
		/// <summary>
		/// Deletes a Role from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="role_name">role_name</param>
		/// <param name="helper">helper</param>
		internal static void DeleteRole(string @role_name, SqlHelper @helper)
		{
			string commandText = "RoleDelete";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@role_name", @role_name));
		
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Creates a new Role object.
		/// </summary>
		/// <returns>The newly created Role object.</returns>
		public static Role CreateRole()
		{
			return InitializeNew<Role>();
		}
		
		/// <summary>
		/// Retrieve information for a Role by a Role's unique identifier.
		/// </summary>
		/// <param name="role_name">role_name</param>
		/// <returns>Role</returns>
		public static Role GetRole(string role_name)
		{
			string commandText = "RoleGet";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@role_name", role_name));
			
			return GetOne<Role>(commandText, parameters);
		}
		
		/// <summary>
		/// Gets a collection Role objects.
		/// </summary>
		/// <returns>The retrieved collection of Role objects.</returns>
		public static EntityList<Role> GetRoles()
		{
			string commandText = "RoleGetAll";
		
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			return GetList<Role>(commandText, parameters);
		}
		
		/// <summary>
        /// Gets a collection Role objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of Role objects.</returns>
        protected static EntityList<Role> GetRoles(string orderBy, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<Role>(SelectFieldList, "FROM [dbo].[Roles]", new List<SqlParameter>(),orderBy,  startRowIndex, pageSize, out totalRows);
        }

		/// <summary>
        /// Gets a collection Role objects.
        /// </summary>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">Page Size</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of Role objects.</returns>
        public static EntityList<Role> GetRoles(int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<Role>(SelectFieldList, "FROM [dbo].[Roles]", new List<SqlParameter>(), null,  startRowIndex, pageSize, out totalRows);
        }
		
		/// <summary>
		/// Gets a collection Role objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <param name="orderBy">the order by clause. Should start with "order by"</param>
		/// <returns>The retrieved collection of Role objects.</returns>
		protected static EntityList<Role> GetRoles(string where, SqlParameter parameter, string orderBy)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetRoles(string.Empty, where, parameters, orderBy);
		}
		
		/// <summary>
		/// Gets a collection Role objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of Role objects.</returns>
		protected static EntityList<Role> GetRoles(string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetRoles(string.Empty, where, parameters, Role.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection Role objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of Role objects.</returns>
		protected static EntityList<Role> GetRoles(string prefix, string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetRoles(prefix, where, parameters, Role.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection Role objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of Role objects.</returns>
		protected static EntityList<Role> GetRoles(string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetRoles(string.Empty, where, parameters, Role.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection Role objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of Role objects.</returns>
		protected static EntityList<Role> GetRoles(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetRoles(prefix, where, parameters, Role.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection Role objects by custom where clause and order by.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <param name="orderBy">the order by clause. Shoudl start with "order by"</param>
		/// <returns>The retrieved collection of Role objects.</returns>
		protected static EntityList<Role> GetRoles(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters, string orderBy)
		{
			string commandText = @"SELECT " + prefix + "" + Role.SelectFieldList + "FROM [dbo].[Roles] " + where + " " + orderBy;			
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				using (IDataReader reader = helper.ExecuteDataReader(commandText, CommandType.Text, parameters))
				{
					return EntityBase.InitializeList<Role>(reader);
				}
			}
		}		
		
		/// <summary>
        /// Gets a collection Address objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="where">where</param>
		/// <param name=parameters">parameters</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of Address objects.</returns>
        protected static EntityList<Role> GetRoles(string orderBy, string where, System.Collections.Generic.List<SqlParameter> parameters, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<Role>(SelectFieldList, "FROM [dbo].[Roles] " + where, parameters, orderBy, startRowIndex, pageSize, out totalRows);			
		}
		
		#endregion
		
		#region Subclasses
		public static partial class RoleProperties
		{
			public const string role_name = "role_name";
			public const string notes = "notes";
		}
		#endregion
	}
}
