/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 09/09/2012 8:49:16 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;

using DocketPlace.Business.Framework;


namespace DocketPlace.Business
{
	/// <summary>
	/// This object represents the properties and methods of a FaultCode.
	/// </summary>
	[Serializable()]
	[DebuggerDisplay("faultcode_id: {faultcode_id}")]
	public partial class FaultCode
	{
		#region Public Properties
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private int _faultcode_id = int.MinValue;
		/// <summary>
		/// faultcode_id
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(true, false, false)]
		public int faultcode_id
		{
			[DebuggerStepThrough()]
			get { return this._faultcode_id; }
			set 
			{
				if (this._faultcode_id != value) 
				{
					this._faultcode_id = value;
					this.IsDirty = true;	
					OnPropertyChanged("faultcode_id");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _description = String.Empty;
		/// <summary>
		/// description
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, false)]
		public string description
		{
			[DebuggerStepThrough()]
			get { return this._description; }
			set 
			{
				if (this._description != value) 
				{
					this._description = value;
					this.IsDirty = true;	
					OnPropertyChanged("description");
				}
			}
		}
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private string _display_message = String.Empty;
		/// <summary>
		/// display_message
		/// </summary>
		[DatabaseColumn()]
		[TypeConverter(typeof(MinToEmptyTypeConverter))]
		[DataObjectField(false, false, true)]
		public string display_message
		{
			[DebuggerStepThrough()]
			get { return this._display_message; }
			set 
			{
				if (this._display_message != value) 
				{
					this._display_message = value;
					this.IsDirty = true;	
					OnPropertyChanged("display_message");
				}
			}
		}
		
		
		
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		private EntityList<Fault> _faultsByfaultcode_ = null;
		/// <summary>
		/// A collection of Fault children objects
		/// </summary>
		public EntityList<Fault> FaultsByfaultcode_
		{
			get 
			{
				if (_faultsByfaultcode_ == null) {
					_faultsByfaultcode_ = DocketPlace.Business.Fault.GetFaultsByfaultcode_(this);
				}
				return _faultsByfaultcode_;
			}
		}	
		#endregion
		
		#region Non-Public Properties
		/// <summary>
		/// Gets the SQL statement for an insert
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string InsertSPName
		{
			get 
			{
				return typeof(FaultCode).Name + "Insert";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for an update by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string UpdateSPName
		{
			get
			{
				return typeof(FaultCode).Name + "Update";
			}
		}
		
		/// <summary>
		/// Gets the SQL statement for a delete by key
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		protected override string DeleteSPName
		{
			get
			{
				return typeof(FaultCode).Name + "Delete";
			}
		}
		#endregion
		
		#region Constructors
		/// <summary>
		/// The default protected constructor
		/// </summary>
		protected FaultCode() { }
		#endregion
		
		#region Public Methods
		/// <summary>
		/// Creates a Fault for this FaultCode object
		/// </summary>
		public Fault CreateFault()
		{
			return DocketPlace.Business.Fault.CreateFaultByfaultcode_(this);
		}
		

        /// <summary>
        /// Refreshes the entity with data from the data source. Child entity objects and entity list objects will be preserved (ie. they will not be replaced with new objects so that references to them are retained, such as bound data controls).
        /// </summary>
        public override void Refresh()
		{
			this.Replace(GetFaultCode(this.faultcode_id));
		}

		#endregion
		
		#region Non-Public Methods
		/// <summary>
		/// This is called before an entity is saved to ensure that any parent entities keys are set properly
		/// </summary>
		protected override void EnsureParentProperties()
		{
		}
		#endregion
		
		#region Static Properties
		/// <summary>
		/// A list of all fields for this entity in the database. It does not include the 
		/// select keyword, or the table information - just the fields. This can be used
		/// for new dynamic methods.
		/// </summary>
		[DebuggerBrowsable(DebuggerBrowsableState.Never)]
		public static string SelectFieldList 
		{
			get 
			{
				return @"
	[FaultCodes].[faultcode_id],
	[FaultCodes].[description],
	[FaultCodes].[display_message]
";
			}
		}
		
		
		/// <summary>
        /// Table Name
        /// </summary>
        public new static string TableName
        {
            get
            {
                return "FaultCodes";
            }
        }

		#endregion
		
		#region Static Methods
		/// <summary>
		/// Insert a FaultCode into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="faultcode_id">faultcode_id</param>
		/// <param name="description">description</param>
		/// <param name="display_message">display_message</param>
		public static void InsertFaultCode(int @faultcode_id, string @description, string @display_message)
		{
            using (SqlHelper helper = new SqlHelper())
            {
                try
                {
                    helper.BeginTransaction();
            		InsertFaultCode(@faultcode_id, @description, @display_message, helper);
                    helper.Commit();
                }
                catch
                {
                    helper.Rollback();
                    throw;
                }
            }
		}

		/// <summary>
		/// Insert a FaultCode into the data store based on the primitive properties. This can be used as the 
		/// insert method for an ObjectDataSource.
		/// </summary>
		/// <param name="faultcode_id">faultcode_id</param>
		/// <param name="description">description</param>
		/// <param name="display_message">display_message</param>
		/// <param name="helper">helper</param>
		internal static void InsertFaultCode(int @faultcode_id, string @description, string @display_message, SqlHelper @helper)
		{
			string commandText = "FaultCodeInsert";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@faultcode_id", EntityBase.GetDatabaseValue(@faultcode_id)));
			parameters.Add(new SqlParameter("@description", EntityBase.GetDatabaseValue(@description)));
			parameters.Add(new SqlParameter("@display_message", EntityBase.GetDatabaseValue(@display_message)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Updates a FaultCode into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="faultcode_id">faultcode_id</param>
		/// <param name="description">description</param>
		/// <param name="display_message">display_message</param>
		public static void UpdateFaultCode(int @faultcode_id, string @description, string @display_message)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try
				{
					helper.BeginTransaction();
					UpdateFaultCode(@faultcode_id, @description, @display_message, helper);
					helper.Commit();
				}
				catch 
				{
					helper.Rollback();	
					throw;
				}
			}
		}
		
		/// <summary>
		/// Updates a FaultCode into the data store based on the primitive properties. This can be used as the 
		/// update method for an ObjectDataSource.
		/// </summary>
		/// <param name="faultcode_id">faultcode_id</param>
		/// <param name="description">description</param>
		/// <param name="display_message">display_message</param>
		/// <param name="helper">helper</param>
		internal static void UpdateFaultCode(int @faultcode_id, string @description, string @display_message, SqlHelper @helper)
		{
			string commandText = "FaultCodeUpdate";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@faultcode_id", EntityBase.GetDatabaseValue(@faultcode_id)));
			parameters.Add(new SqlParameter("@description", EntityBase.GetDatabaseValue(@description)));
			parameters.Add(new SqlParameter("@display_message", EntityBase.GetDatabaseValue(@display_message)));
			
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Deletes a FaultCode from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="faultcode_id">faultcode_id</param>
		public static void DeleteFaultCode(int @faultcode_id)
		{
			using (SqlHelper helper = new SqlHelper()) 
			{
				try 
				{
					helper.BeginTransaction();
					DeleteFaultCode(@faultcode_id, helper);
					helper.Commit();
				} 
				catch 
				{
					helper.Rollback();
					throw;
				}
			}
		}
		
		/// <summary>
		/// Deletes a FaultCode from the data store based on the primitive primary keys. This can be used as the 
		/// delete method for an ObjectDataSource.
		/// </summary>
		/// <param name="faultcode_id">faultcode_id</param>
		/// <param name="helper">helper</param>
		internal static void DeleteFaultCode(int @faultcode_id, SqlHelper @helper)
		{
			string commandText = "FaultCodeDelete";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@faultcode_id", @faultcode_id));
		
			@helper.Execute(commandText, CommandType.StoredProcedure, parameters);
		}
		
		/// <summary>
		/// Creates a new FaultCode object.
		/// </summary>
		/// <returns>The newly created FaultCode object.</returns>
		public static FaultCode CreateFaultCode()
		{
			return InitializeNew<FaultCode>();
		}
		
		/// <summary>
		/// Retrieve information for a FaultCode by a FaultCode's unique identifier.
		/// </summary>
		/// <param name="faultcode_id">faultcode_id</param>
		/// <returns>FaultCode</returns>
		public static FaultCode GetFaultCode(int faultcode_id)
		{
			string commandText = "FaultCodeGet";
			
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			parameters.Add(new SqlParameter("@faultcode_id", faultcode_id));
			
			return GetOne<FaultCode>(commandText, parameters);
		}
		
		/// <summary>
		/// Gets a collection FaultCode objects.
		/// </summary>
		/// <returns>The retrieved collection of FaultCode objects.</returns>
		public static EntityList<FaultCode> GetFaultCodes()
		{
			string commandText = "FaultCodeGetAll";
		
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			return GetList<FaultCode>(commandText, parameters);
		}
		
		/// <summary>
        /// Gets a collection FaultCode objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of FaultCode objects.</returns>
        protected static EntityList<FaultCode> GetFaultCodes(string orderBy, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<FaultCode>(SelectFieldList, "FROM [dbo].[FaultCodes]", new List<SqlParameter>(),orderBy,  startRowIndex, pageSize, out totalRows);
        }

		/// <summary>
        /// Gets a collection FaultCode objects.
        /// </summary>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">Page Size</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of FaultCode objects.</returns>
        public static EntityList<FaultCode> GetFaultCodes(int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<FaultCode>(SelectFieldList, "FROM [dbo].[FaultCodes]", new List<SqlParameter>(), null,  startRowIndex, pageSize, out totalRows);
        }
		
		/// <summary>
		/// Gets a collection FaultCode objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <param name="orderBy">the order by clause. Should start with "order by"</param>
		/// <returns>The retrieved collection of FaultCode objects.</returns>
		protected static EntityList<FaultCode> GetFaultCodes(string where, SqlParameter parameter, string orderBy)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetFaultCodes(string.Empty, where, parameters, orderBy);
		}
		
		/// <summary>
		/// Gets a collection FaultCode objects by custom where clause.
		/// </summary>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of FaultCode objects.</returns>
		protected static EntityList<FaultCode> GetFaultCodes(string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetFaultCodes(string.Empty, where, parameters, FaultCode.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection FaultCode objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameter">The parameter that is in the where clause</param>
		/// <returns>The retrieved collection of FaultCode objects.</returns>
		protected static EntityList<FaultCode> GetFaultCodes(string prefix, string where, SqlParameter parameter)
		{
			System.Collections.Generic.List<SqlParameter> parameters = new System.Collections.Generic.List<SqlParameter>();
			
			parameters.Add(parameter);
						
			return GetFaultCodes(prefix, where, parameters, FaultCode.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection FaultCode objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of FaultCode objects.</returns>
		protected static EntityList<FaultCode> GetFaultCodes(string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetFaultCodes(string.Empty, where, parameters, FaultCode.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection FaultCode objects by custom where clause.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <returns>The retrieved collection of FaultCode objects.</returns>
		protected static EntityList<FaultCode> GetFaultCodes(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters)
		{
			return GetFaultCodes(prefix, where, parameters, FaultCode.DefaultSortOrder);
		}
		
		/// <summary>
		/// Gets a collection FaultCode objects by custom where clause and order by.
		/// </summary>
		/// <param name="prefix">The prefix clause allows you to inject a distinct or top clause.</param>
		/// <param name="where">The where clause to use for the query. Should be parameterized and start with "where"</param>
		/// <param name="parameters">The parameters that are listed in the where clause</param>
		/// <param name="orderBy">the order by clause. Shoudl start with "order by"</param>
		/// <returns>The retrieved collection of FaultCode objects.</returns>
		protected static EntityList<FaultCode> GetFaultCodes(string prefix, string where, System.Collections.Generic.List<SqlParameter> parameters, string orderBy)
		{
			string commandText = @"SELECT " + prefix + "" + FaultCode.SelectFieldList + "FROM [dbo].[FaultCodes] " + where + " " + orderBy;			
			
			using (SqlHelper helper = new SqlHelper()) 
			{
				using (IDataReader reader = helper.ExecuteDataReader(commandText, CommandType.Text, parameters))
				{
					return EntityBase.InitializeList<FaultCode>(reader);
				}
			}
		}		
		
		/// <summary>
        /// Gets a collection Address objects.
        /// </summary>
		/// <param name="orderBy">order by</param>
		/// <param name="where">where</param>
		/// <param name=parameters">parameters</param>
		/// <param name="startRowIndex">Start Row Index</param>
		/// <param name="pageSize">PageSize</param>
		/// <param name="totalRows">Total rows</param>
        /// <returns>The retrieved collection of Address objects.</returns>
        protected static EntityList<FaultCode> GetFaultCodes(string orderBy, string where, System.Collections.Generic.List<SqlParameter> parameters, int startRowIndex, int pageSize, out long totalRows)
        {
            return GetList<FaultCode>(SelectFieldList, "FROM [dbo].[FaultCodes] " + where, parameters, orderBy, startRowIndex, pageSize, out totalRows);			
		}
		
		#endregion
		
		#region Subclasses
		public static partial class FaultCodeProperties
		{
			public const string faultcode_id = "faultcode_id";
			public const string description = "description";
			public const string display_message = "display_message";
		}
		#endregion
	}
}
