/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 28/12/2009 6:20:18 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will NOT be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.SqlClient;
using System.Text;

using DocketPlace.Business.Framework;

namespace DocketPlace.Business
{
	/// <summary>
	/// This object represents the properties and methods of a Store.
	/// </summary>
	public partial class Store : EntityBase
	{
          #region Public Properties



          public string combined_address
          {

               get { return this.address + " " + this.suburb + " " + this.state; }

          }

          #endregion


		
          public string ResetPassword()
          {
               string new_password = System.IO.Path.ChangeExtension(System.IO.Path.GetRandomFileName(), null);

               try
               {
				this.password = new_password; 
                    this.Save();
                    return new_password;
               }
               catch (Exception ex)
               {
                    throw ex;
               }
          }
	}
}
