/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 11/08/2012 4:48:52 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;

namespace DocketPlace.Business.Framework
{
	/// <summary>
	/// A custom attribute used to identify the database column name of a property of a custom business object.
	/// </summary>
	public class DatabaseColumnAttribute : Attribute
	{
		public DatabaseColumnAttribute(string name)
		{
			_name = name;
		}
		
		public DatabaseColumnAttribute()
		{
			
		}

		private string _name = string.Empty;
        /// <summary>
        /// The database column name
        /// </summary>
		public string Name
		{
			get { return _name; }
		}
	}
}
