/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 28/12/2009 6:18:18 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will NOT be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Collections;
using System.Collections.ObjectModel;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;
using System.Data;

namespace DocketPlace.Business.Framework
{
    /// <summary>
    /// Read / Write List of objects
    /// </summary>
    /// <typeparam name="T">object type</typeparam>
    public partial class EntityListBase<T> : System.ComponentModel.BindingList<T>
    {

	}
}
