/*------------------------------------------------------------------------
<generated>
     This code was generated by The NuSoft Framework v3.0
     Generated at 11/08/2012 4:48:53 PM.

     The NuSoft Framework is an open source project developed
     by NuSoft Solutions (http://www.nusoftsolutions.com).
     The latest version of the framework templates and detailed license
     is available at http://www.codeplex.com/NuSoftFramework.

     This file will be overwritten when regenerating your code.
</generated>
------------------------------------------------------------------------*/

using System;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace DocketPlace.Business.Framework
{
    /// <summary>
    /// Summary description for SqlHelper
    /// </summary>
    public partial class SqlHelper
    {
    }
}