//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.EsendexAccount {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.esendex.ems.soapinterface", ConfigurationName="EsendexAccount.AccountServiceSoap")]
    public interface AccountServiceSoap {
        
        // CODEGEN: Generating message contract since message GetMessageLimitRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/GetMessageLimit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApp.EsendexAccount.GetMessageLimitResponse GetMessageLimit(WebApp.EsendexAccount.GetMessageLimitRequest request);
        
        // CODEGEN: Generating message contract since message GetSentMessagesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/GetSentMessages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApp.EsendexAccount.GetSentMessagesResponse GetSentMessages(WebApp.EsendexAccount.GetSentMessagesRequest request);
        
        // CODEGEN: Generating message contract since message GetAccountFeaturesRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/GetAccountFeatures", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApp.EsendexAccount.GetAccountFeaturesResponse GetAccountFeatures(WebApp.EsendexAccount.GetAccountFeaturesRequest request);
        
        // CODEGEN: Generating message contract since message GetAccountStateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/GetAccountState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebApp.EsendexAccount.GetAccountStateResponse GetAccountState(WebApp.EsendexAccount.GetAccountStateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public partial class MessengerHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string accountField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public partial class AccountState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string referenceField;
        
        private string addressField;
        
        private string serviceAliasField;
        
        private int messageLimitField;
        
        private AccountFeature featuresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceAlias {
            get {
                return this.serviceAliasField;
            }
            set {
                this.serviceAliasField = value;
                this.RaisePropertyChanged("ServiceAlias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int MessageLimit {
            get {
                return this.messageLimitField;
            }
            set {
                this.messageLimitField = value;
                this.RaisePropertyChanged("MessageLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public AccountFeature Features {
            get {
                return this.featuresField;
            }
            set {
                this.featuresField = value;
                this.RaisePropertyChanged("Features");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public enum AccountFeature {
        
        /// <remarks/>
        None = 1,
        
        /// <remarks/>
        ServiceAliasing = 2,
        
        /// <remarks/>
        Inbox = 4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public partial class message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string originatorField;
        
        private string recipientField;
        
        private string bodyField;
        
        private System.DateTime sentatField;
        
        private System.DateTime receivedatField;
        
        private MessageType typeField;
        
        private MessageStatusCode statusField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime sentat {
            get {
                return this.sentatField;
            }
            set {
                this.sentatField = value;
                this.RaisePropertyChanged("sentat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime receivedat {
            get {
                return this.receivedatField;
            }
            set {
                this.receivedatField = value;
                this.RaisePropertyChanged("receivedat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public MessageType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public MessageStatusCode status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public enum MessageType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        SmartMessage,
        
        /// <remarks/>
        Unicode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public enum MessageStatusCode {
        
        /// <remarks/>
        Queued,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Delivered,
        
        /// <remarks/>
        Failed,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageLimit", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetMessageLimitRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public WebApp.EsendexAccount.MessengerHeader MessengerHeader;
        
        public GetMessageLimitRequest() {
        }
        
        public GetMessageLimitRequest(WebApp.EsendexAccount.MessengerHeader MessengerHeader) {
            this.MessengerHeader = MessengerHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageLimitResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetMessageLimitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public int GetMessageLimitResult;
        
        public GetMessageLimitResponse() {
        }
        
        public GetMessageLimitResponse(int GetMessageLimitResult) {
            this.GetMessageLimitResult = GetMessageLimitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSentMessages", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetSentMessagesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public WebApp.EsendexAccount.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=1)]
        public int month;
        
        public GetSentMessagesRequest() {
        }
        
        public GetSentMessagesRequest(WebApp.EsendexAccount.MessengerHeader MessengerHeader, int year, int month) {
            this.MessengerHeader = MessengerHeader;
            this.year = year;
            this.month = month;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSentMessagesResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetSentMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public message[] GetSentMessagesResult;
        
        public GetSentMessagesResponse() {
        }
        
        public GetSentMessagesResponse(message[] GetSentMessagesResult) {
            this.GetSentMessagesResult = GetSentMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountFeatures", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetAccountFeaturesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public WebApp.EsendexAccount.MessengerHeader MessengerHeader;
        
        public GetAccountFeaturesRequest() {
        }
        
        public GetAccountFeaturesRequest(WebApp.EsendexAccount.MessengerHeader MessengerHeader) {
            this.MessengerHeader = MessengerHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountFeaturesResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetAccountFeaturesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public WebApp.EsendexAccount.AccountFeature GetAccountFeaturesResult;
        
        public GetAccountFeaturesResponse() {
        }
        
        public GetAccountFeaturesResponse(WebApp.EsendexAccount.AccountFeature GetAccountFeaturesResult) {
            this.GetAccountFeaturesResult = GetAccountFeaturesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountState", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetAccountStateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public WebApp.EsendexAccount.MessengerHeader MessengerHeader;
        
        public GetAccountStateRequest() {
        }
        
        public GetAccountStateRequest(WebApp.EsendexAccount.MessengerHeader MessengerHeader) {
            this.MessengerHeader = MessengerHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAccountStateResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetAccountStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public WebApp.EsendexAccount.AccountState GetAccountStateResult;
        
        public GetAccountStateResponse() {
        }
        
        public GetAccountStateResponse(WebApp.EsendexAccount.AccountState GetAccountStateResult) {
            this.GetAccountStateResult = GetAccountStateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountServiceSoapChannel : WebApp.EsendexAccount.AccountServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceSoapClient : System.ServiceModel.ClientBase<WebApp.EsendexAccount.AccountServiceSoap>, WebApp.EsendexAccount.AccountServiceSoap {
        
        public AccountServiceSoapClient() {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.EsendexAccount.GetMessageLimitResponse WebApp.EsendexAccount.AccountServiceSoap.GetMessageLimit(WebApp.EsendexAccount.GetMessageLimitRequest request) {
            return base.Channel.GetMessageLimit(request);
        }
        
        public int GetMessageLimit(WebApp.EsendexAccount.MessengerHeader MessengerHeader) {
            WebApp.EsendexAccount.GetMessageLimitRequest inValue = new WebApp.EsendexAccount.GetMessageLimitRequest();
            inValue.MessengerHeader = MessengerHeader;
            WebApp.EsendexAccount.GetMessageLimitResponse retVal = ((WebApp.EsendexAccount.AccountServiceSoap)(this)).GetMessageLimit(inValue);
            return retVal.GetMessageLimitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.EsendexAccount.GetSentMessagesResponse WebApp.EsendexAccount.AccountServiceSoap.GetSentMessages(WebApp.EsendexAccount.GetSentMessagesRequest request) {
            return base.Channel.GetSentMessages(request);
        }
        
        public message[] GetSentMessages(WebApp.EsendexAccount.MessengerHeader MessengerHeader, int year, int month) {
            WebApp.EsendexAccount.GetSentMessagesRequest inValue = new WebApp.EsendexAccount.GetSentMessagesRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.year = year;
            inValue.month = month;
            WebApp.EsendexAccount.GetSentMessagesResponse retVal = ((WebApp.EsendexAccount.AccountServiceSoap)(this)).GetSentMessages(inValue);
            return retVal.GetSentMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.EsendexAccount.GetAccountFeaturesResponse WebApp.EsendexAccount.AccountServiceSoap.GetAccountFeatures(WebApp.EsendexAccount.GetAccountFeaturesRequest request) {
            return base.Channel.GetAccountFeatures(request);
        }
        
        public WebApp.EsendexAccount.AccountFeature GetAccountFeatures(WebApp.EsendexAccount.MessengerHeader MessengerHeader) {
            WebApp.EsendexAccount.GetAccountFeaturesRequest inValue = new WebApp.EsendexAccount.GetAccountFeaturesRequest();
            inValue.MessengerHeader = MessengerHeader;
            WebApp.EsendexAccount.GetAccountFeaturesResponse retVal = ((WebApp.EsendexAccount.AccountServiceSoap)(this)).GetAccountFeatures(inValue);
            return retVal.GetAccountFeaturesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApp.EsendexAccount.GetAccountStateResponse WebApp.EsendexAccount.AccountServiceSoap.GetAccountState(WebApp.EsendexAccount.GetAccountStateRequest request) {
            return base.Channel.GetAccountState(request);
        }
        
        public WebApp.EsendexAccount.AccountState GetAccountState(WebApp.EsendexAccount.MessengerHeader MessengerHeader) {
            WebApp.EsendexAccount.GetAccountStateRequest inValue = new WebApp.EsendexAccount.GetAccountStateRequest();
            inValue.MessengerHeader = MessengerHeader;
            WebApp.EsendexAccount.GetAccountStateResponse retVal = ((WebApp.EsendexAccount.AccountServiceSoap)(this)).GetAccountState(inValue);
            return retVal.GetAccountStateResult;
        }
    }
}
